/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herd;

import java.awt.Container;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author jtbea
 */
public class LoginController extends javax.swing.JPanel {
    
    private String userName;
    private String passwd;
    final private Model aModel;
    final private LoginView aView;
    final private LoginFrame logFrame;
    
    /**
     * Creates new form HERDLogin
     */
    public LoginController(final Model aModel, final LoginView aView, final LoginFrame frame) {
        
        initComponents();
        this.aModel = aModel;
        this.aView = aView;
        logFrame = frame;
        
        username_TextField.setText("");
        password_TextField.setText("");
        
        logButton.addActionListener(new ActionListener()
        {
               @Override public void actionPerformed(ActionEvent e)
                {
                    userName = username_TextField.getText();
                    passwd = password_TextField.getText();
                    
                    if (aModel.approved(userName, passwd) == true)
                    {
                        aModel.resetAttempt();
                        username_TextField.setText("");
                        password_TextField.setText("");
                        
                        logFrame.setVisible(false);
                        ProfileFrame proFrame = new ProfileFrame(aModel, logFrame);
                    }
                    else
                    {   
                        aView.repaint();
                    }
                }
        });
        add(logButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        username_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        password_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        logButton = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        username_TextField.setText("jTextField1");

        jLabel1.setText("Username");

        password_TextField.setText("jTextField2");

        jLabel2.setText("Password");

        logButton.setText("Log In");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(username_TextField))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(logButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(logButton)
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logButton;
    private javax.swing.JTextField password_TextField;
    private javax.swing.JTextField username_TextField;
    // End of variables declaration//GEN-END:variables



}
