/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herd;

import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author jerensuzuki
 */
public class ProfileSearchView extends javax.swing.JPanel {

    /**
     * Creates new form ProfileSearchView
     */
    public ProfileSearchView() {
        initComponents();
    }

    private Model aModel;
    private String currentTag;
    
    public ProfileSearchView(Model aModel) {
        this.aModel = aModel;
        currentTag = "All";
        initComponents();
    }
   
    String [] tags = {"Music", "Food"};
    JComboBox tagList = new JComboBox(tags);
    
    @SuppressWarnings("unchecked")

    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Font font = new Font("Verdana", Font.BOLD, 12);
        g.setFont(font);
      
        String titleEvents = "Local Events:";
        g.drawString(titleEvents, 20, 70);
        
        ArrayList<Events> filterdEvents;
        
        if (currentTag == "All")
        {
            filterdEvents = aModel.getAllEvents();
        }
        else
        {
            filterdEvents = aModel.getFilteredEvents(currentTag);
        }
       
        int position = 75;
        for (Events event : filterdEvents)
        {
            String eventName = event.getTitle();
            position = position + 15;
            g.drawString(eventName, 20, position);
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Music", "Sports", "Food", "Party" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        currentTag = String.valueOf(jComboBox1.getSelectedItem());
        this.repaint();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
