/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package herd;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Jeren
 */
public class ProfileSavedEventView extends javax.swing.JPanel {

    Model aModel;
    ArrayList<Events> saved;

    /**
     * Creates new form ProfileSavedEventView
     */
    public ProfileSavedEventView(Model aModel) {
        initComponents();
        this.aModel = aModel;
        saved = this.aModel.getSavedEvents();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        setBackground(Color.orange);

        String title1 = "Your saved events are";
        g.drawString(title1, 40, 110);

        int position1 = 140;
        int position2 = 145;
        int offset = 0;
        if (saved != null) {
            for (Events event : saved) {
                String eventName = event.getTitle();
                String eventDescription = event.getDescription();
                g.drawString(eventName, 40, position1 + offset * 15);
                g.drawString(eventDescription, 45, position2 + offset * 15);
                offset++;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
