
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author jtbea
 */
public class ProfileController extends javax.swing.JPanel {

    private String activeTag;
    private Model aModel;
    private final ProfileView profileView;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        addSavedEventButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        createEventButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        deleteSavedEventButton = new javax.swing.JButton();
        addTagButton = new javax.swing.JButton();
        tagsToActionOn = new javax.swing.JComboBox<>();
        removeTagButton = new javax.swing.JButton();

        addSavedEventButton.setText("Add to Saved");
        addSavedEventButton.setToolTipText("ADD TO SAVED EVENTs");

        logOutButton.setText("Log Out");

        createEventButton.setText("Create an Event");
        createEventButton.setActionCommand("");

        jTextField1.setToolTipText("Event ID");

        deleteSavedEventButton.setText("Remove from Saved");
        deleteSavedEventButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSavedEventButtonActionPerformed(evt);
            }
        });

        addTagButton.setText("Add Tag");
        addTagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTagButtonActionPerformed(evt);
            }
        });

        tagsToActionOn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Party", "Music", "Food", "Sports" }));
        tagsToActionOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsToActionOnActionPerformed(evt);
            }
        });

        removeTagButton.setText("Remove Tag");
        removeTagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTagButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteSavedEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSavedEventButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeTagButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(tagsToActionOn, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTagButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createEventButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagsToActionOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createEventButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSavedEventButton)
                            .addComponent(addTagButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteSavedEventButton)
                            .addComponent(removeTagButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tagsToActionOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagsToActionOnActionPerformed
        activeTag = String.valueOf(tagsToActionOn.getSelectedItem());
    }//GEN-LAST:event_tagsToActionOnActionPerformed

    private void addTagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTagButtonActionPerformed
        aModel.addInterests(activeTag);
        profileView.repaint();
    }//GEN-LAST:event_addTagButtonActionPerformed

    private void removeTagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTagButtonActionPerformed
        aModel.removeInterests(activeTag);
        profileView.repaint();
    }//GEN-LAST:event_removeTagButtonActionPerformed

    private void deleteSavedEventButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSavedEventButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSavedEventButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSavedEventButton;
    private javax.swing.JButton addTagButton;
    private javax.swing.JButton createEventButton;
    private javax.swing.JButton deleteSavedEventButton;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton removeTagButton;
    private javax.swing.JComboBox<String> tagsToActionOn;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form HERDController
     *
     * @param Model
     * @param aView
     * @param savedEvents
     * @param proFrame
     * @param logFrame
     */
    public ProfileController(Model Model, ProfileView aView, ProfileSavedEventView savedEvents, ProfileFrame proFrame, LoginFrame logFrame) {
        
        initComponents();
        profileView = aView;
        aModel = Model;
        setBackground(Color.green);
        

        logOutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                proFrame.dispose();
                logFrame.setVisible(true);
            }
        });
        add(logOutButton);

//         "Save events"
        addSavedEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                aModel.setSavedEvent(Integer.parseInt(jTextField1.getText()));
                savedEvents.repaint();
            }
        });
        add(addSavedEventButton);

        deleteSavedEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                aModel.removeSavedEvent(Integer.parseInt(jTextField1.getText()));
                savedEvents.repaint();
            }
        });
        add(deleteSavedEventButton);
        
        createEventButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                proFrame.setVisible(false);
                CreateFrame cFrame = new CreateFrame(aModel, proFrame);
            }
        });
        add(createEventButton);
        
    }
    

}
